#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yellow='\033[0;33m'
no_color='\033[0m'

echo -e "${yellow}Linting:${no_color}"
FORCE_COLOR=1 pnpm -s lint

echo -e "\n${yellow}Formatting:${no_color}"
FORCE_COLOR=1 pnpm -s format

echo -e "\n${yellow}Spell Checking:${no_color}"
FORCE_COLOR=1 pnpm -s spell-check